name: Docker Image CI

on:
  pull_request:
    branches: [ "release" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-go@v4
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        ls 
        ls ../
        echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin docker.io
        docker build . --tag ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPO }}
        docker push docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPO }}
